export const weatherData = {
  monthlyTemperature: [
    { month: 'Jan', temp: 15, feelsLike: 17 },
    { month: 'Fev', temp: 18, feelsLike: 19 },
    { month: 'Mar', temp: 22, feelsLike: 24 },
    { month: 'Abr', temp: 25, feelsLike: 26 },
    { month: 'Mai', temp: 28, feelsLike: 29 },
    { month: 'Jun', temp: 30, feelsLike: 31 },
    { month: 'Jul', temp: 35, feelsLike: 37 },
    { month: 'Aug', temp: 33, feelsLike: 34 },
    { month: 'Set', temp: 29, feelsLike: 30 },
    { month: 'Out', temp: 24, feelsLike: 25 },
    { month: 'Nov', temp: 20, feelsLike: 21 },
    { month: 'Dez', temp: 17, feelsLike: 18 },
  ],
  weeklyRainVolume: [
    { week: 'Semana 1', rain: 20 },
    { week: 'Semana 2', rain: 35 },
    { week: 'Semana 3', rain: 10 },
    { week: 'Semana 4', rain: 50 },
  ],
  dailyHumidity: [
    { day: 'Seg', humidity: 70 },
    { day: 'Ter', humidity: 65 },
    { day: 'Qua', humidity: 80 },
    { day: 'Qui', humidity: 75 },
    { day: 'Sex', humidity: 60 },
    { day: 'Sáb', humidity: 85 },
    { day: 'Dom', humidity: 90 },
  ],
  hottestDays: [
    { date: '2025-04-01', temp: 36 },
    { date: '2025-04-03', temp: 38 },
    { date: '2025-04-05', temp: 37 },
  ],
  windSpeedTrend: [
    { day: 'Seg', speed: 10 },
    { day: 'Ter', speed: 12 },
    { day: 'Qua', speed: 8 },
    { day: 'Qui', speed: 15 },
    { day: 'Sex', speed: 9 },
    { day: 'Sáb', speed: 14 },
    { day: 'Dom', speed: 11 },
  ],
  temperatureHeatmap: [
    { hour: '0h', temp: 22, feelsLike: 21 },
    { hour: '6h', temp: 20, feelsLike: 19 },
    { hour: '12h', temp: 28, feelsLike: 31 },
    { hour: '18h', temp: 26, feelsLike: 28 },
  ],

};
