export const weatherData = {
  monthlyTemperature: [
    { month: 'Jan', temp: 15 },
    { month: 'Feb', temp: 18 },
    { month: 'Mar', temp: 22 },
    { month: 'Apr', temp: 25 },
    { month: 'May', temp: 28 },
    { month: 'Jun', temp: 30 },
    { month: 'Jul', temp: 35 },
    { month: 'Aug', temp: 33 },
    { month: 'Sep', temp: 29 },
    { month: 'Oct', temp: 24 },
    { month: 'Nov', temp: 20 },
    { month: 'Dec', temp: 17 },
  ],
  weeklyRainVolume: [
    { week: 'Week 1', rain: 20 },
    { week: 'Week 2', rain: 35 },
    { week: 'Week 3', rain: 10 },
    { week: 'Week 4', rain: 50 },
  ],
  dailyHumidity: [
    { day: 'Mon', humidity: 70 },
    { day: 'Tue', humidity: 65 },
    { day: 'Wed', humidity: 80 },
    { day: 'Thu', humidity: 75 },
    { day: 'Fri', humidity: 60 },
    { day: 'Sat', humidity: 85 },
    { day: 'Sun', humidity: 90 },
  ],
  hottestDays: [
    { date: '2025-04-01', temp: 36 },
    { date: '2025-04-03', temp: 38 },
    { date: '2025-04-05', temp: 37 },
  ],
  windSpeedTrend: [
    { day: 'Mon', speed: 10 },
    { day: 'Tue', speed: 12 },
    { day: 'Wed', speed: 8 },
    { day: 'Thu', speed: 15 },
    { day: 'Fri', speed: 9 },
    { day: 'Sat', speed: 14 },
    { day: 'Sun', speed: 11 },
  ],
  temperatureHeatmap: [
    { hour: '0h', temp: 22 },
    { hour: '6h', temp: 20 },
    { hour: '12h', temp: 28 },
    { hour: '18h', temp: 26 },
  ],
};
